### PR TITLE
Jeonsang

### PR DESCRIPTION
**Pull request by sanghyunJ**
what are changed
- refactored project module (from single module to multi module)
- added spring batch for learning hashtag via word2vec

FYI
to run batch application, you should set vm option like attached image.

스크린샷 2020-06-25 오전 12 07 17

### CODE REVIEW

**Comment by jinsumin** [comment]
LGTM

**Review by ljh0940 — APPROVED** [review]
LGTM

**Review by jinsumin — APPROVED** [review]
LGTM

**Review by hyun132 — APPROVED** [review]

**Review by JungEunPyo — APPROVED** [review]
good

**Review by ljh0940 — APPROVED** [review]

**Pull request merged**
